### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by praneybehl** [baysao/meteor-riot-layout#1]
Hey,
Thanks for creating the package, I always wanted to tryout RiotJS. 
Just wondering if it can be used with Flow router? also if you may be able to point to an example it will be really helpful.

cheers!

**Comment by alphashuro** [comment]
this code seems to be working when rendering one tag

FlowRouter.route('/', {
	action() {
		RiotLayout.render('dashboard');
	}
});

But I would also like to see an example that includes a layout

**Comment by praneybehl** [comment]
Sorry I should have been more clear. I tried earlier but I think you can't get regions to work.

**Comment by baysao** [comment]
@praneybehl i have add some explain in documents and example.
Feel free to try it.

**Comment by praneybehl** [comment]
@baysao thanks mate, what I meant to say is that with meteor-riot-layout you can't use layout regions like in https://github.com/kadirahq/blaze-layout or meteor-react-layout 
Please refer : https://github.com/kadirahq/meteor-react-layout#using-inside-flow-router
```js
FlowRouter.route('/post/:_id', {
  name: 'post',
  subscriptions: function(params) {
    this.register('singlePost', Meteor.subscribe('singlePost', params._id));
  },
  action: function(params) {
    ReactLayout.render(BlogLayout, {
      content: <PostPage _id={params._id} />
    });
  }
```

See the {content: "sometag"} in:
```js
    ReactLayout.render(BlogLayout, {
      content: <PostPage _id={params._id} />
    });
```
which is the ability to render regions/yields is not supported

**Comment by alphashuro** [comment]
I actually got layouts to work by using riot.mount to mount the layout passed in options

*layout.tag*
````    
<layout>
  <a href='home'>Home</a>
  <div name="main"></div>
	
  riot.mount(this.main, opts.main);
</layout>
````
*dashboard.tag*
````
<dashboard>
  <h1>Dashboard</h1>
</dashboard>
````
*route*
````
FlowRouter.route('/', {
  action() {
      RiotLayout.render('layout', { main: 'dashboard' });
  }
});
````

Though something in my gut tells me this is not really how we should be doing it, so a proper example with layouts would still be much appreciated if it is any different from this

**Comment by praneybehl** [comment]
Yes that is how I am using, but there is no way to use it out of the box.

**Comment by baysao** [comment]
Hi @praneybehl @alphashuro . Now you can define DOM element in layout for later fill component by RiotLayout as
```
<welcome>
    <h3>Welcome, { opts.name }</h3>
     <div id="header"></div>
     <div id="main"></div>
     <div id="footer"></div>
    <a href="/dashboard">Dashboard</a>
</welcome>
```
Please check example

**Comment by alphashuro** [comment]
Thank you

**Comment by praneybehl** [comment]
@baysao cheers, thanks mate :+1:
